package com.example.aston5

object Constants {
    const val FIRST_FRAGMENT_RESULT_KEY_INT = "FIRST_FRAGMENT_RESULT_KEY_INT"
    const val FIRST_FRAGMENT_BUNDLE_KEY_INT = "FIRST_FRAGMENT_BUNDLE_KEY_INT"
    const val FIRST_FRAGMENT_RESULT_KEY = "FIRST_FRAGMENT_RESULT_KEY"
    const val FIRST_FRAGMENT_BUNDLE_KEY = "FIRST_FRAGMENT_BUNDLE_KEY"
    const val TELEPHONE_NUMBER_BUNDLE_KEY = "TELEPHONE_NUMBER_BUNDLE_KEY"
    const val TELEPHONE_NUMBER_RESULT_KEY = "TELEPHONE_NUMBER_BUNDLE_KEY"
    const val KEY_NAME = "key1"
    const val KEY_TELEPHONE = "key2"
    const val KEY_INT = "KEY_INT"
}